AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  GithubOAuthSecretParameterA4DAD33A:
    Type: AWS::SSM::Parameter::Value<String>
    Default: github-gplassard-oauth
    NoEcho: true
Resources:
  Webhook:
    Type: Custom::CodebuildGithubWebhook
    Version: "1.0"
    Properties:
      ServiceToken: arn:aws:lambda:eu-west-1:147597503572:function:cfn-github-webhook-dev-githubWebhook
      CodebuildProjectName: !Ref AWS::StackName
      GithubOAuth: !Ref GithubOAuthSecretParameterA4DAD33A
  MyProjectRole9BBE5233:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
  MyProjectRoleDefaultPolicyB19B7C29:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: MyProject39F7B0AE
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: MyProject39F7B0AE
                    - :*
        Version: "2012-10-17"
      PolicyName: MyProjectRoleDefaultPolicyB19B7C29
      Roles:
        - Ref: MyProjectRole9BBE5233
  MyProject39F7B0AE:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/ubuntu-base:14.04
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      ServiceRole:
        Fn::GetAtt:
          - MyProjectRole9BBE5233
          - Arn
      Source:
        Auth:
          Resource:
            Ref: GithubOAuthSecretParameterA4DAD33A
          Type: OAUTH
        BuildSpec: test-buildspec.yml
        Location: https://github.com/gplassard/aws-cdk-codepipeline.git
        ReportBuildStatus: true
        Type: GITHUB
      BadgeEnabled: true
      Name: !Ref AWS::StackName